name: Fun CI/CD Demo

on: [push, pull_request]

jobs:
  run-fortune:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Run Fortune Teller
        run: python fortune.py

